# -*- coding: utf-8 -*-
"""_main_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeoB0fLUpIkCBN2zC8wRUQfhXEB-T8IT
"""

import sys
from .topsis import topsis

if __name__ == "__main__":
    if len(sys.argv) != 5:
        print("Usage: python -m topsis_package <InputDataFile> <Weights> <Impacts> <ResultFileName>")
    else:
        _, input_file, weights, impacts, output_file = sys.argv
        topsis(input_file, weights, impacts, output_file)